using HtmlBuilder.Tags.FormTags;
using HtmlBuilder.Tags.InteractiveTags;
using HtmlBuilder.Tags.MediaTags;
using HtmlBuilder.Tags.ScriptAndMetaTags;
using HtmlBuilder.Tags.StructuralTags;
using HtmlBuilder.Tags.StylingTags;
using HtmlBuilder.Tags.TableTags;
using HtmlBuilder.Tags.TextContentTag;

namespace HtmlBuilder;
public interface IHtmlVisitor
{
    void Visit(Datalist tag);
    void Visit(Fieldset tag);
    void Visit(Form tag);
    void Visit(Input tag);
    void Visit(Label tag);
    void Visit(Legend tag);
    void Visit(Option tag);
    void Visit(Output tag);
    void Visit(Select tag);
    void Visit(Textarea tag);
    void Visit(A tag);
    void Visit(Button tag);
    void Visit(Details tag);
    void Visit(Dialog tag);
    void Visit(Menu tag);
    void Visit(Summary tag);
    void Visit(Audio tag);
    void Visit(Iframe tag);
    void Visit(Img tag);
    void Visit(Source tag);
    void Visit(Track tag);
    void Visit(Video tag);
    void Visit(Base tag);
    void Visit(Link tag);
    void Visit(Meta tag);
    void Visit(Noscript tag);
    void Visit(Script tag);
    void Visit(Style tag);
    void Visit(Article tag);
    void Visit(Aside tag);
    void Visit(Body tag);
    void Visit(Div tag);
    void Visit(Footer tag);
    void Visit(Head tag);
    void Visit(Header tag);
    void Visit(Html tag);
    void Visit(Main tag);
    void Visit(Nav tag);
    void Visit(Section tag);
    void Visit(B tag);
    void Visit(Em tag);
    void Visit(I tag);
    void Visit(Mark tag);
    void Visit(S tag);
    void Visit(Small tag);
    void Visit(Span tag);
    void Visit(Strong tag);
    void Visit(Sub tag);
    void Visit(Sup tag);
    void Visit(U tag);
    void Visit(Caption tag);
    void Visit(Col tag);
    void Visit(Colgroup tag);
    void Visit(Table tag);
    void Visit(Tbody tag);
    void Visit(Td tag);
    void Visit(Tfoot tag);
    void Visit(Th tag);
    void Visit(Thead tag);
    void Visit(Tr tag);
    void Visit(Blockquote tag);
    void Visit(Br tag);
    void Visit(Dd tag);
    void Visit(Dl tag);
    void Visit(Dt tag);
    void Visit(Figcaption tag);
    void Visit(Figure tag);
    void Visit(H1 tag);
    void Visit(H2 tag);
    void Visit(H3 tag);
    void Visit(H4 tag);
    void Visit(H5 tag);
    void Visit(H6 tag);
    void Visit(Hr tag);
    void Visit(Li tag);
    void Visit(Ol tag);
    void Visit(P tag);
    void Visit(Pre tag);
    void Visit(Ul tag);
}
